# Generated by Django 4.2.5 on 2023-10-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_agency'),
        ('products', '0007_alter_product_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
