# Generated by Django 4.2.5 on 2023-10-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_supplier'),
        ('supply', '0003_delete_partner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='Partner',
        ),
    ]
