# Generated by Django 4.2.5 on 2023-10-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_supply_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='release_date',
        ),
    ]
