# Generated by Django 4.2.5 on 2023-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_remove_supply_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='release_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания заявки'),
        ),
    ]
