# Generated by Django 4.2.5 on 2023-10-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_supply_release_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'node_type__in': ['ИП', 'Розничная сеть']}, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='supply.partner', verbose_name='Организация'),
        ),
    ]
