# Generated by Django 4.2.5 on 2023-10-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_manufacturer'),
        ('supply', '0010_remove_supply_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product', verbose_name='Продукты'),
        ),
    ]
