# Generated by Django 4.2.5 on 2023-10-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0012_alter_supply_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='is_active',
        ),
    ]
