# Generated by Django 4.2.5 on 2023-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название продукта')),
                ('model', models.CharField(max_length=50, verbose_name='модель продукта')),
                ('release_date', models.DateField(verbose_name='дата выхода продукта')),
                ('is_active', models.BooleanField(default=True, verbose_name='активация продукта')),
            ],
        ),
    ]
