# Generated by Django 4.2.5 on 2023-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата выхода продукта'),
        ),
    ]
