# Generated by Django 4.2.5 on 2023-10-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
        ('products', '0004_alter_product_options_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.partner', verbose_name='Организация'),
        ),
    ]
