# Generated by Django 4.2.5 on 2023-10-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_supply_products'),
        ('products', '0008_remove_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.partner', verbose_name='Организация роизводитель'),
        ),
    ]
